spring:
  config:
    import:
      - optional:file:../.env[.properties]

  threads:
    virtual:
      enabled: true

  # Configurações do DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  # Configurações do Hibernate (opcional)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      oauth2:
        enabled: true

  mvc:
    log-request-details: true

  # Configurações de Multipart (Upload de Arquivos)
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  # Configurações do DevTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[br.org.kinflasy.clients.UserClient]": DEBUG
    "[br.org.kinflasy.apis.churches.clients.PersonClient]": DEBUG

springdoc:
  api-docs:
    path: /api-docs
  use-fqn: true
  open-api:
    servers:
      - url: ${API_URL:http://localhost:8080}
  swagger-ui:
    doc-expansion: none

openfga:
  api-url: ${OPENFGA_HTTP_URL}
  credentials:
    method: api-token
    config:
      api-token: ${OPENFGA_API_TOKEN}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
  openfga:
    model-file-path: ${OPENFGA_MODEL_FILE}
  storage:
    provider: ${STORAGE_PROVIDER}
    url: ${STORAGE_URL}
    bucket: ${STORAGE_BUCKET}
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
