spring:
  config:
    import:
      - optional:file:../.env[.properties]

  # Configurações do DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  # Configurações do Hibernate (opcional)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.use_sql_comments]": true

  cloud:
    openfeign:
      oauth2:
        enabled: true

  mvc:
    log-request-details: true

  # Configurações do DevTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[br.org.kinflasy.clients.UserClient]": DEBUG
    "[br.org.kinflasy.apis.churches.clients.PersonClient]": DEBUG

springdoc:
  api-docs:
    path: /api-docs
  use-fqn: true
  open-api:
    servers:
      - url: ${API_URL:http://localhost:8080}

openfga:
  api-url: ${OPENFGA_HTTP_URL}
  credentials:
    method: api-token
    config:
      api-token: ${OPENFGA_API_TOKEN}
  
app:
  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
  openfga:
    model-file-path: ${OPENFGA_MODEL_FILE}
