spring:
  config:
    import:
      - optional:file:../.env[.properties]

  # Configurações do DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  # Configurações do Hibernate (opcional)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.use_sql_comments]": true

  cloud:
    openfeign:
      oauth2:
        enabled: true
      client:
        config:
          execution-usersApi:
            url: ${USERS_API_URL}
          auth-usersApi:
            url: ${USERS_API_URL}
          churches-addressesApi:
            url: ${ADDRESS_API_URL}
          churches-peopleApi:
            url: ${PEOPLE_API_URL}
          churches-inactivePeopleApi:
            url: ${INACTIVE_PEOPLE_API_URL}
          churches-usersApi:
            url: ${USERS_API_URL}
          people-addressesApi:
            url: ${ADDRESS_API_URL}
          people-churchesApi:
            url: ${CHURCHES_API_URL}

  # Configurações do DevTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

logging:
  level:
    "[br.org.kinflasy.clients.UserClient]": DEBUG
    "[br.org.kinflasy.apis.churches.clients.PersonClient]": DEBUG

springdoc:
  api-docs:
    path: /api-docs
  use-fqn: true
  open-api:
    servers:
      - url: ${API_URL:http://localhost:8080}

openfga:
  api-url: http://${OPENFGA_HTTP_HOST}:${OPENFGA_HTTP_PORT}
  store-id: ${OPENFGA_STORE_ID}
  authorization-model-id: ${OPENFGA_AUTHORIZATION_MODEL_ID}

app:
  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
