networks:
  openfga:

services:
  # Serviço para o PostgreSQL
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - ${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  #     volumes:
  #       - pg-data:/var/lib/postgresql/data

  # Serviço para a aplicação Spring Boot
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_HOST: db

  # Serviço para o PostgreSQL
  openfga-db:
    image: postgres:17.5-alpine3.21
    container_name: openfga-db
    restart: always
    ports:
      - "${OPENFGA_DATABASE_PORT}:5432"
    expose:
      - ${OPENFGA_DATABASE_PORT}
    environment:
      - POSTGRES_USER=${OPENFGA_DATABASE_USER}
      - POSTGRES_PASSWORD=${OPENFGA_DATABASE_PASSWORD}
      - POSTGRES_DB=${OPENFGA_DATABASE_NAME}
    networks:
      - openfga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OPENFGA_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  #     volumes:
  #       - pg-data:/var/lib/postgresql/data

  migrate:
    depends_on:
      openfga-db:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://${OPENFGA_DATABASE_USER}:${OPENFGA_DATABASE_PASSWORD}@openfga-db:${DATABASE_PORT}/${OPENFGA_DATABASE_NAME}?sslmode=disable
    networks:
      - openfga

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://${OPENFGA_DATABASE_USER}:${OPENFGA_DATABASE_PASSWORD}@openfga-db:5432/${OPENFGA_DATABASE_NAME}?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_HTTP_ADDR=0.0.0.0:${OPENFGA_HTTP_PORT}
    command: run
    networks:
      - openfga
    ports:
      # Needed for the http server
      - "${OPENFGA_HTTP_PORT}:${OPENFGA_HTTP_PORT}"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

      # docker pull openfga/cli; docker run -it openfga/cli
  fga-cli:
    image: openfga/cli
    environment:
      - name=value


# volumes:
#   pg-data:
