# Configurações do DataSource
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # Configurações do Hibernate (opcional)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  # Configurações do DevTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
