spring:
  config:
    import:
    - file:../../.env[.properties]

  cloud:
    openfeign:
      client:
        config:
          churches-api:
            url: ${CHURCHES_API_URL}
          church-base-api:
            url: ${CHURCH_BASE_API_URL}